### ISSUE TITLE
Error with fresh install - "undefined method `haml_tag'"

### ISSUE THREAD

**Issue by alximik00** [gma/nesta#189]
Preconditions: 
- installed nesta as said here in 'Getting started': http://nestacms.com/
- cloned demo content
- ran the application
- opened http://localhost:8080/

Results an error:

```
NoMethodError - undefined method `haml_tag' for #<Nesta::App:0x00007f9b82b32ca0>:
	/Users/alximik00/.rvm/gems/ruby-2.7.2/gems/nesta-0.12.0/lib/nesta/navigation.rb:44:in `display_breadcrumbs'
	/Users/alximik00/.rvm/gems/ruby-2.7.2/gems/nesta-0.12.0/views/page.haml:2:in `__tilt_2940'
	/Users/alximik00/.rvm/gems/ruby-2.7.2/gems/tilt-2.0.11/lib/tilt/template.rb:181:in `call'
	/Users/alximik00/.rvm/gems/ruby-2.7.2/gems/tilt-2.0.11/lib/tilt/template.rb:181:in `evaluate'
	/Users/alximik00/.rvm/gems/ruby-2.7.2/gems/tilt-2.0.11/lib/tilt/template.rb:109:in `render'
	/Users/alximik00/.rvm/gems/ruby-2.7.2/gems/sinatra-2.2.2/lib/sinatra/base.rb:856:in `render'
	/Users/alximik00/.rvm/gems/ruby-2.7.2/gems/sinatra-2.2.2/lib/sinatra/base.rb:714:in `haml'
	/Users/alximik00/.rvm/gems/ruby-2.7.2/gems/nesta-0.12.0/lib/nesta/overrides.rb:6:in `haml'
	/Users/alximik00/.rvm/gems/ruby-2.7.2/gems/nesta-0.12.0/lib/nesta/app.rb:88:in `block in <class:App>'
```	

Haml version installed is '6.0.3' - this will be default with current Gemfile. Works well with haml 5.2.2.

**Comment by gma** [comment]
Thanks for that, great bug report. I'll push a fix today and release a new gem.
